amazonProperties:
  endpointUrl: https://s3.ap-south-100.amazonaws.com
  accessKey: AKIAJFYA2FQRHBHBSHBK
  secretKey: tsQGJwA5lRtRKuAY63wjhbdhb6Z9x91w6RcXA/
  bucketName: cadenza-imagesss/testing-product
